<?= '<?xml version="1.0" encoding="UTF-8" ?>'; ?>
<!-- This is a WordPress eXtended RSS file generated by WordPress as an export of your site. -->
<!-- It contains information about your site's posts, pages, comments, categories, and other content. -->
<!-- You may use this file to transfer that content from one site to another. -->
<!-- This file is not intended to serve as a complete backup of your site. -->

<!-- To import this information into a WordPress site follow these steps: -->
<!-- 1. Log in to that site as an administrator. -->
<!-- 2. Go to Tools: Import in the WordPress admin panel. -->
<!-- 3. Install the "WordPress" importer from the list. -->
<!-- 4. Activate & Run Importer. -->
<!-- 5. Upload this file using the form provided on that page. -->
<!-- 6. You will first be asked to map the authors in this export file to users -->
<!--    on the site. For each author, you may choose to map to an -->
<!--    existing user on the site or to create a new user. -->
<!-- 7. WordPress will then import each of the posts, pages, comments, categories, etc. -->
<!--    contained in this file into your site. -->

<!-- generator="WordPress/4.9.4" created="{{ \Carbon\Carbon::now()->format('Y-m-d h:i') }}" -->
<rss version="2.0"
     xmlns:excerpt="http://wordpress.org/export/1.2/excerpt/"
     xmlns:content="http://purl.org/rss/1.0/modules/content/"
     xmlns:wfw="http://wellformedweb.org/CommentAPI/"
     xmlns:dc="http://purl.org/dc/elements/1.1/"
     xmlns:wp="http://wordpress.org/export/1.2/"
>
    <channel>
        <title>Budgets</title>
        <link>http://localhost/budgets-wordpress</link>
        <description></description>
        <pubDate>{{ substr(\Carbon\Carbon::now()->toDayDateTimeString(), 0, -3) }}:10 +0000</pubDate>
        <language>en-US</language>
        <wp:wxr_version>1.2</wp:wxr_version>
        <wp:base_site_url>http://localhost/budgets-wordpress</wp:base_site_url>
        <wp:base_blog_url>http://localhost/budgets-wordpress</wp:base_blog_url>

        <wp:author>
            <wp:author_id>1</wp:author_id>
            <wp:author_login><![CDATA[mediaship.com@gmail.com]]></wp:author_login>
            <wp:author_email><![CDATA[info@budgets.jp]]></wp:author_email>
            <wp:author_display_name><![CDATA[admin]]></wp:author_display_name>
            <wp:author_first_name><![CDATA[]]></wp:author_first_name>
            <wp:author_last_name><![CDATA[]]></wp:author_last_name>
        </wp:author>

        <generator>https://wordpress.org/?v=4.9.4</generator>
        @foreach($categories as $category)
            @if(!empty($category->products))
                <?php
                    if ($category->title == 'その他（ハッピ・ゼッケン・スタッフジャンパー）') {
                        $category->title = 'ハッピ・ゼッケン・スタッフジャンパー';
                    }
                ?>
                @foreach($category->products as $product)
                    <?php $product->image = ''; ?>
                    <item>
                        <title>{!! $product->title !!}</title>
                        <link>http://localhost/budgets-wordpress/{{ \Carbon\Carbon::now()->format('Y/m/d') }}/{!! strTolower(urlencode($product->title)) !!}/</link>
                        <pubDate>{{ substr(\Carbon\Carbon::now()->toDayDateTimeString(), 0, -3) }}:15 +0000</pubDate>
                        <dc:creator><![CDATA[admin]]></dc:creator>
                        <guid isPermaLink="false">http://localhost/budgets-wordpress/?p={!! $lastPostId !!}</guid>
                        <description></description>
                        <content:encoded>
                            <![CDATA[description <a href="http://localhost/budgets-wordpress/wp-admin/edit.php?category_name={!! 'parent-category-t-shirt' !!}">{!! $category->title !!}</a>]]>
                        </content:encoded>
                        <excerpt:encoded><![CDATA[]]></excerpt:encoded>
                        <wp:post_id>{!! $lastPostId !!}</wp:post_id>
                        <wp:post_date><![CDATA[{{ \Carbon\Carbon::now()->format('Y-m-d h:i:s') }}]]></wp:post_date>
                        <wp:post_date_gmt><![CDATA[{{ \Carbon\Carbon::now()->format('Y-m-d h:i:s') }}]]>
                        </wp:post_date_gmt>
                        <wp:comment_status><![CDATA[open]]></wp:comment_status>
                        <wp:ping_status><![CDATA[open]]></wp:ping_status>
                        <wp:post_name><![CDATA[{!! strToLower(urlencode($product->title . $lastPostId)) !!}]]></wp:post_name>
                        <wp:status><![CDATA[publish]]></wp:status>
                        <wp:post_parent>0</wp:post_parent>
                        <wp:menu_order>0</wp:menu_order>
                        <wp:post_type><![CDATA[post]]></wp:post_type>
                        <wp:post_password><![CDATA[]]></wp:post_password>
                        <wp:is_sticky>0</wp:is_sticky>
                        <category domain="category" nicename="{!! strToLower(urlencode($category->title)) !!}">
                            <![CDATA[{!! $category->title !!}]]>
                        </category>
                        <wp:postmeta>
                            <wp:meta_key><![CDATA[product_id]]></wp:meta_key>
                            <wp:meta_value><![CDATA[{!! $product->id !!}]]></wp:meta_value>
                        </wp:postmeta>
                        <wp:postmeta>
                            <wp:meta_key><![CDATA[colors]]></wp:meta_key>
                            <wp:meta_value><![CDATA[{!! $product->color_total !!}]]></wp:meta_value>
                        </wp:postmeta>
                        <wp:postmeta>
                            <wp:meta_key><![CDATA[size]]></wp:meta_key>
                            <wp:meta_value><![CDATA[{!! $product->size !!}]]></wp:meta_value>
                        </wp:postmeta>
                        <wp:postmeta>
                            <wp:meta_key><![CDATA[price]]></wp:meta_key>
                            <wp:meta_value><![CDATA[{!! $product->tool_price . '円' !!}]]></wp:meta_value>
                        </wp:postmeta>
                        <wp:postmeta>
                            <wp:meta_key><![CDATA[material]]></wp:meta_key>
                            <wp:meta_value><![CDATA[{{ $product->material }}]]></wp:meta_value>
                        </wp:postmeta>
                        <wp:postmeta>
                            <wp:meta_key><![CDATA[deleted]]></wp:meta_key>
                            <wp:meta_value><![CDATA[0]]></wp:meta_value>
                        </wp:postmeta>
                        <wp:postmeta>
                            <wp:meta_key><![CDATA[image]]></wp:meta_key>
                            @if (!empty($product->productColorMain) && !empty($product->productColorMain->productColorSideMain))
                                <?php $product->image = $product->productColorMain->productColorSideMain->image_url; ?>
                            @else
                                <?php
                                    if ($product->productColors) {
                                        foreach ($product->productColors as $productColor) {
                                            if (!empty($productColor->productColorSides)) {
                                                foreach ($productColor->productColorSides as $productColorSide) {
                                                    $product->image = $product->productColorMain->productColorSideMain->image_url;
                                                    break;
                                                }
                                            }
                                            if (!empty($product->image)) {
                                                break;
                                            }
                                        }
                                    }
                                ?>
                            @endif
                            <wp:meta_value><![CDATA[{!! $product->image !!}]]></wp:meta_value>
                        </wp:postmeta>
                    </item>
                    <?php $lastPostId += 1; ?>
                @endforeach
            @endif
        @endforeach
    </channel>
</rss>